name: '☁️ AWS Public ECR Login'
description: 'GitHub Action to login against a AWS'

on:
  workflow_call:
    secrets:
      AWS_SECRET_ACCESS_KEY:
        description: 'Password or PAT (Personal Access Token) used to log against the AWS'
        required: true
    inputs:
      registry:
        type: string
        default: 'public.ecr.aws'
        description: 'Server address of AWS Public ECR. If not set then will default to Docker Hub'
        required: false
      username:
        type: string
        description: 'Username used to log against the AWS'
        required: false
      password:
        type: string
        description: 'Password or PAT (Personal Access Token) used to log against the AWS'
        required: false
      ecr:
        type: string
        default: 'auto'
        description: 'Specifies whether the given registry is ECR (auto, true or false)'
        required: false
      logout:
        type: boolean
        default: true
        description: 'Log out from the AWS at the end of a job'
        required: false

jobs:
  job-aws-public-ecr-login-action:
    name: Job - AWS Public ECR Login
    runs-on: ubuntu-22.04
    environment: ${{ github.ref }}
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Step - AWS Public ECR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ vars.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecr: ${{ inputs.ecr }}
          logout: ${{ inputs.logout }}
